### ISSUE TITLE
Create nice to have REST resources

### ISSUE THREAD

**Issue by Lazzzer** [Lazzzer/llm-structurizer#22]
### Description

**As an user**, **I would like to** have additional endpoints and REST resources **so** I can register and authorise my application and enjoy additional functionalities provided by LLMs such as question answering over my data.

### Acceptance criteria

- [ ] ~~The API exposes a `retrievers` resource that can query external data stores and return response in natural language.~~
- [ ] ~~The API exposes a `applications` resource that handles the registration and authorisation of applications.~~
- [ ] ~~The API exposes a `auth` resource that handles API keys generations and management.~~

### Requirements
- #3 
- #29 

### Notes:

**Update [2023-07-11] :**

The criterias will not be fullfilled for the last sprint of this project. A generic prompt implementation will be available instead as a nice to have feature.
