### ISSUE TITLE
Implement modifications discussed in sprint 1 review

### ISSUE THREAD

**Issue by Lazzzer** [Lazzzer/llm-structurizer#24]
### Description

**As a developer**, **I would like to** have the implemented modifications from the last sprint review **so** my API has the desired features and specifications.

### Acceptance criteria

- [x] The global app rate-limiter can be increased.
- [x] The PDF validation doesn't need to check if the content starts with the magic number.
- [x] 422 error codes of PDF text parsing need to be better worded.
- [x] Users give their own API key for the language model they want to use. They can choose any available model.
- [x] The `refine` option in json text structuring is a nullable object used to specify the wanted chunking size and overlap.
- [x] The `refine` option should display the number of calls made to the LLM in the result.
- [x] The text structuring endpoints accept a nullable `debug` field to append the generation logs to the result.
- [x] 422 errors for text structuring should be more explanatory (request failed because of context size?) if possible.
- [x] The analysis endpoint can also provide an explanation field.

### Requirements
- None.
