### ISSUE TITLE
Create parsers resource

### ISSUE THREAD

**Issue by Lazzzer** [Lazzzer/llm-structurizer#4]
### Description

**As a user**, **I would like to** use endpoints of the API to process my files **so** I can extract the unstructured text from them.

### Acceptance criteria

- [x] The `parsers` resource exposes REST endpoints that accept file uploads or urls.
- [x] The `parsers` resource is correctly documented in the OpenAPI specification.
- [x] The `parsers` resource must at least be able to process searchable PDF files.
- [x] The `parsers` resource processes safely the files and return the generated text in its responses.
- [x] The `parsers` resource implementation contains appropriate tests.

### Requirements
- #6 
- #7 
- #12
