### ISSUE TITLE
Create structured-data resource

### ISSUE THREAD

**Issue by Lazzzer** [Lazzzer/llm-structurizer#5]
### Description

**As a user**, **I would like to** use endpoints of the API to process my unstructured texts **so** I can obtain processable data in specific formats such as JSON.

### Acceptance criteria

- [x] The `structured-data` resource exposes REST endpoints that accept text inputs.
- [x] The `structured-data` resource is correctly documented in the OpenAPI specification.
- [x] The `structured-data` resource must at least provide JSON objects as structured data.
- [x] The `structured-data` POST endpoints enable pertinent fields to configure the text structuration.
- [x] The `structured-data` resource exposes endpoint(s) that can verify previous text structurations.
- [x] The `structured-data` resource implementation contains appropriate tests.

### Requirements
- #15 
- #16 
- #20 

### Notes
Links : 
- [LangChain](https://js.langchain.com/docs/)
